services:

  django:
    build: .
    ports:
      - "${PORT}:${PORT}"
    working_dir: /home/${UNAME}/${PROJECT_DIR}
    command: python manage.py runserver 0.0.0.0:${PORT}
    environment:
      - TZ=Europe/Copenhagen
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - ./${PROJECT_DIR}:/home/${UNAME}/${PROJECT_DIR}
    networks:
      - default

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: metaInfo
      POSTGRES_USER: datUser
      POSTGRES_PASSWORD: renteMester2400
    networks:
      - default


networks:
  default:
    name: meta_subscribe
