services:
  django:
    build: .
    ports:
      - "${PORT}:${PORT}"
    working_dir: /home/${UNAME}/${PROJECT_DIR}
    command: python manage.py runserver 0.0.0.0:${PORT}
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./${PROJECT_DIR}:/home/${UNAME}/${PROJECT_DIR}
    networks:
      - default

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: metaInfo
      POSTGRES_USER: datUser
      POSTGRES_PASSWORD: renteMester2400
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - default
networks:
  default:
    name: meta_subscribe
