services:

  django:
    build: .
    restart: always
    ports:
      - "${PORT}:3000"
    working_dir: /app
    environment:
      TZ: Europe/Copenhagen
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./${PROJECT_DIR}:/app
    networks:
      - default

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - default


networks:
  default:
    name: meta_subscribe
